---
title: "Kaggle Predict Rent in New York"
author: "NING YANG"
date: '2021-11-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(knitr)
library(ggplot2)
library(plyr)
library(dplyr)
library(corrplot)
library(caret)
library(gridExtra)
library(scales)
library(Rmisc)
library(ggrepel)
library(randomForest)
library(psych)
library(xgboost)
library(naniar)
library(gsubfn)
library(qdapTools)
library(stringi)
library(vtreat)
library(mice)
```


```{r }
#Import data
setwd("/Users/yangning/Desktop/Academic semester/2021fall/5200/kaggle/rentData/")
data=read.csv("analysisData.csv",header=TRUE,fill=TRUE,na.strings="")
scoringData=read.csv('scoringData.csv',header=TRUE,fill=TRUE,na.strings="")
#Initial exploration
dim(data)
str(data)
ggplot(data=data[!is.na(data$price),],aes(x=price))+
  geom_histogram(fill="blue",binwidth=70)+
  scale_x_continuous(breaks=seq(0,10000,by=100),labels=comma)
which.max(data$price)
#Check Missing Data
#1.data
miss_scan_count(data=data,search=list("N/A"))#check hidden missing values
data<-replace_with_na_all(data,~.x%in% c("N/A"))#replace hidden missing values with NA
sum(is.na(data))
data1<-data
#2.scoringdata
miss_scan_count(data =scoringData,search=list("N/A"))#check hidden missing values
scoringData<-replace_with_na_all(scoringData,~.x %in% c("N/A"))#replace hidden missing values with NA
sum(is.na(scoringData))
scoringData1<-scoringData
scoringData<-scoringData1
```


```{r }
#deal with host_response_rate
#1.data
data$host_response_rate<-gsub("%"," ",data$host_response_rate)#remove "%"
data$host_response_rate<-as.numeric(data$host_response_rate)*0.01
str(data$host_response_rate)
data$host_acceptance_rate<-gsub("%"," ",data$host_acceptance_rate)#remove "%"
data$host_acceptance_rate<-as.numeric(data$host_acceptance_rate)*0.01
str(data$host_acceptance_rate)
#2.scoringdata
scoringData$host_response_rate<- gsub("%"," ",scoringData$host_response_rate)
scoringData$host_response_rate<-as.numeric(scoringData$host_response_rate)*0.01
scoringData$host_acceptance_rate<- gsub("%"," ",scoringData$host_acceptance_rate)
scoringData$host_acceptance_rate<-as.numeric(scoringData$host_acceptance_rate)*0.01
```


```{r }
#deal with date variables
#1.data
Sys.setlocale("LC_TIME","English")
data$host_since<-as.Date(as.character(data$host_since),format="%Y-%m-%d")#change the format
data$first_review<-as.Date(as.character(data$first_review),format="%Y-%m-%d")
data$last_review<-as.Date(as.character(data$last_review),format="%Y-%m-%d")
today<-Sys.Date()#today's date
data$host_since_diff<-as.numeric(difftime(today,data$host_since))#create days until today 
data$first_review_diff<-as.numeric(difftime(today,data$first_review))
data$last_review_diff<-as.numeric(difftime(today,data$last_review))
data$review_length<-data$first_review_diff-data$last_review_diff#create review days between the two
#2.Scoringdata
scoringData$host_since<-as.Date(as.character(scoringData$host_since), format="%Y-%m-%d")
scoringData$first_review<-as.Date(as.character(scoringData$first_review), format="%Y-%m-%d")
scoringData$last_review<-as.Date(as.character(scoringData$last_review), format="%Y-%m-%d")
today<-Sys.Date()
scoringData$host_since_diff<-as.numeric(difftime(today,scoringData$host_since))
scoringData$first_review_diff<-as.numeric(difftime(today,scoringData$first_review))
scoringData$last_review_diff<-as.numeric(difftime(today,scoringData$last_review))
scoringData$review_length<-scoringData$first_review_diff-scoringData$last_review_diff
```


```{r }
#deal with amenities variable
#1.data
data$amenities=gsub("\\.","",data$amenities)#remoce the dot to avoid variables occur twice
data$amenities<-stringr::str_replace_all(data$amenities,"\\s","")#remove the space from the string on both side
data$amenities=noquote(data$amenities)#remove ""
data=cbind(data,mtabulate(strsplit(as.character(data$amenities),",")))
colnames(data)[which(colnames(data)=='Selfcheck-in')]='Selfcheck_in'#Correct the format of strings
colnames(data)[which(colnames(data)=='Family/kidfriendly')]='Family_kidfriendly'
#2.scoringdata
scoringData$amenities=gsub("\\.","",scoringData$amenities)
scoringData$amenities<-stringr::str_replace_all(scoringData$amenities,"\\s","")  
scoringData$amenities=noquote(scoringData$amenities)
scoringData=cbind(scoringData,mtabulate(strsplit(as.character(scoringData$amenities),',')))
colnames(scoringData)[which(colnames(scoringData)=='Selfcheck-in')]='Selfcheck_in'
colnames(scoringData)[which(colnames(scoringData)=='Family/kidfriendly')]='Family_kidfriendly'
```


```{r }
#change varibales types
#1.data
airbnb.impute<-data
airbnb.impute$room_type<-as.factor(airbnb.impute$room_type)
airbnb.impute$bed_type<-as.factor(airbnb.impute$bed_type)
airbnb.impute$beds<-as.numeric(airbnb.impute$beds)
airbnb.impute$has_availability<-as.factor(airbnb.impute$has_availability)
airbnb.impute$instant_bookable<-as.factor(airbnb.impute$instant_bookable)
airbnb.impute$require_guest_profile_picture<-as.factor(airbnb.impute$require_guest_profile_picture)
airbnb.impute$reviews_per_month<-as.numeric(airbnb.impute$reviews_per_month)
airbnb.impute$host_is_superhost<-as.factor(airbnb.impute$host_is_superhost)
airbnb.impute$neighbourhood_group_cleansed<-as.factor(airbnb.impute$neighbourhood_group_cleansed)
airbnb.impute$neighbourhood_cleansed<-as.factor(airbnb.impute$neighbourhood_cleansed)
airbnb.impute$is_location_exact<-as.factor(airbnb.impute$is_location_exact)
airbnb.impute$property_type<-as.factor(airbnb.impute$property_type)
airbnb.impute$cancellation_policy<-as.factor(airbnb.impute$cancellation_policy)
airbnb.impute$host_listings_count <-as.numeric(airbnb.impute$host_listings_count)
airbnb.impute$host_total_listings_count <-as.numeric(airbnb.impute$host_total_listings_count)
airbnb.impute$host_has_profile_pic<-as.factor(airbnb.impute$host_has_profile_pic)
airbnb.impute$host_identity_verified<-as.factor(airbnb.impute$host_identity_verified)
airbnb.impute$require_guest_phone_verification<-as.factor(airbnb.impute$require_guest_phone_verification)
airbnb.impute$cleaning_fee<-as.numeric(airbnb.impute$cleaning_fee)
airbnb.impute$host_response_time<-as.factor(airbnb.impute$host_response_time)
airbnb.impute$is_business_travel_ready <-as.factor(airbnb.impute$is_business_travel_ready )
airbnb.impute$requires_license<-as.factor(airbnb.impute$requires_license )
airbnb.impute$security_deposit<-as.numeric(airbnb.impute$security_deposit)
airbnb.impute$calendar_updated<-as.factor(airbnb.impute$calendar_updated)
#2.scoring data
scoringData$room_type<-as.factor(scoringData$room_type)
scoringData$bed_type<-as.factor(scoringData$bed_type)
scoringData$beds<-as.numeric(scoringData$beds)
scoringData$has_availability<-as.factor(scoringData$has_availability)
scoringData$instant_bookable<-as.factor(scoringData$instant_bookable)
scoringData$require_guest_profile_picture<-as.factor(scoringData$require_guest_profile_picture)
scoringData$reviews_per_month<-as.numeric(scoringData$reviews_per_month)
scoringData$host_is_superhost<-as.factor(scoringData$host_is_superhost)
scoringData$neighbourhood_group_cleansed<-as.factor(scoringData$neighbourhood_group_cleansed)
scoringData$neighbourhood_cleansed<-as.factor(scoringData$neighbourhood_cleansed)
scoringData$is_location_exact<-as.factor(scoringData$is_location_exact)
scoringData$property_type<-as.factor(scoringData$property_type)
scoringData$cancellation_policy<-as.factor(scoringData$cancellation_policy)
scoringData$host_listings_count <-as.numeric(scoringData$host_listings_count)
scoringData$host_total_listings_count <-as.numeric(scoringData$host_total_listings_count)
scoringData$host_has_profile_pic<-as.factor(scoringData$host_has_profile_pic)
scoringData$host_identity_verified<-as.factor(scoringData$host_identity_verified)
scoringData$require_guest_phone_verification<-as.factor(scoringData$require_guest_phone_verification)
scoringData$cleaning_fee<-as.numeric(scoringData$cleaning_fee)
scoringData$host_response_time<-as.factor(scoringData$host_response_time)
scoringData$is_business_travel_ready <-as.factor(scoringData$is_business_travel_ready )
scoringData$requires_license<-as.factor(scoringData$requires_license )
scoringData$security_deposit<-as.numeric(scoringData$security_deposit)
scoringData$calendar_updated<-as.factor(scoringData$calendar_updated)
```


```{r }
#imputing missing data for numeric variables-mean value
#1.data
airbnb.impute$host_response_rate[is.na(airbnb.impute$host_response_rate)]<-mean(airbnb.impute$host_response_rate,                                                                              na.rm=TRUE)
airbnb.impute$cleaning_fee[is.na(airbnb.impute$cleaning_fee)]<-mean(airbnb.impute$cleaning_fee,na.rm=TRUE)
airbnb.impute$security_deposit[is.na(airbnb.impute$security_deposit)]<-mean(airbnb.impute$security_deposit,na.rm=TRUE)
airbnb.impute$beds[is.na(airbnb.impute$beds)]<-mean(airbnb.impute$beds,na.rm=TRUE)
airbnb.impute$host_listings_count[is.na(airbnb.impute$host_listings_count)]<-mean(airbnb.impute$host_listings_count,na.rm=TRUE)
airbnb.impute$host_total_listings_count[is.na(airbnb.impute$host_total_listings_count)]<-mean(airbnb.impute$host_total_listings_count,na.rm=TRUE)
airbnb.impute$host_acceptance_rate [is.na(airbnb.impute$host_acceptance_rate )]<-mean(airbnb.impute$host_acceptance_rate ,na.rm=TRUE)
airbnb.impute$reviews_per_month[is.na(airbnb.impute$reviews_per_month)]<-mean(airbnb.impute$reviews_per_month,na.rm=TRUE)
#2.socringdata
scoringData$host_response_rate[is.na(scoringData$host_response_rate)]<-mean(scoringData$host_response_rate,
                                                                            na.rm=TRUE)
scoringData$cleaning_fee[is.na(scoringData$cleaning_fee)]<-mean(scoringData$cleaning_fee,na.rm=TRUE)
scoringData$security_deposit[is.na(scoringData$security_deposit)]<-mean(scoringData$security_deposit,na.rm=TRUE)
scoringData$beds[is.na(scoringData$beds)]<-mean(scoringData$beds,na.rm=TRUE)
scoringData$host_listings_count[is.na(scoringData$host_listings_count)]<-mean(scoringData$host_listings_count,na.rm=TRUE)
scoringData$host_total_listings_count[is.na(scoringData$host_total_listings_count)]<-mean(scoringData$host_total_listings_count,na.rm=TRUE)
scoringData$host_acceptance_rate [is.na(scoringData$host_acceptance_rate )]<-mean(scoringData$host_acceptance_rate ,na.rm=TRUE)
scoringData$reviews_per_month[is.na(scoringData$reviews_per_month)]<-mean(scoringData$reviews_per_month,na.rm=TRUE)
```


```{r }
#select variables- significant variables from liner regression 
selection_data<-airbnb.impute%>%
  select(price,neighbourhood_group_cleansed,host_listings_count,room_type,host_is_superhost,
         accommodates,bathrooms,bedrooms,beds,bed_type,security_deposit,
         cleaning_fee, guests_included,extra_people, minimum_nights,
         maximum_nights,minimum_minimum_nights, maximum_minimum_nights,
         minimum_maximum_nights,minimum_nights_avg_ntm, maximum_nights_avg_ntm,
         availability_30,availability_60,availability_90,cancellation_policy,
         availability_365,number_of_reviews,number_of_reviews_ltm,
         review_scores_rating,review_scores_accuracy,review_scores_cleanliness,
         review_scores_checkin,review_scores_communication,review_scores_location,
         review_scores_value,reviews_per_month,host_since_diff
         ,last_review_diff,first_review_diff,review_length,Elevator,Family_kidfriendly 
         ,Freestreetparking,Kitchen,Lockonbedroomdoor,
         TV,Wifi,Airconditioning,Kitchen,Heating,Washer,Dryer,Smokedetector,
         Carbonmonoxidedetector,Firstaidkit,Fireextinguisher,Essentials,Shampoo,
         Lockonbedroomdoor,Hangers,Hairdryer,Iron,Laptopfriendlyworkspace,
         Selfcheck_in,Smartlock,Privatelivingroom,Privateentrance,
         Hotwater,Bedlinens,Microwave,
         Refrigerator,Dishwasher,Dishesandsilverware,Cookingbasics,Oven,
         Stove,Gardenorbackyard,Privatelivingroom,Coffeemaker )
View(colSums(is.na(selection_data)))
clean.data<-na.omit(selection_data)#omit some NA values of categorical variables 
sum(is.na(clean.data))
str(clean.data)

#2.scoringdata
selection_scoringData<-scoringData%>%
  select(neighbourhood_group_cleansed,host_listings_count,
         room_type,host_is_superhost,
         accommodates,bathrooms,bedrooms,beds,bed_type,security_deposit,
         cleaning_fee, guests_included,extra_people, minimum_nights,
         maximum_nights,minimum_minimum_nights, maximum_minimum_nights,
         minimum_maximum_nights,minimum_nights_avg_ntm, maximum_nights_avg_ntm,
         availability_30,availability_60,availability_90,cancellation_policy,
         availability_365,number_of_reviews,number_of_reviews_ltm,
         review_scores_rating,review_scores_accuracy,review_scores_cleanliness,
         review_scores_checkin,review_scores_communication,review_scores_location,
         review_scores_value,reviews_per_month,host_since_diff
         ,last_review_diff,first_review_diff,review_length,Elevator,Family_kidfriendly 
         ,Freestreetparking,Kitchen,Lockonbedroomdoor,
         TV,Wifi,Airconditioning,Kitchen,Heating,Washer,Dryer,Smokedetector,
         Carbonmonoxidedetector,Firstaidkit,Fireextinguisher,Essentials,Shampoo,
         Lockonbedroomdoor,Hangers,Hairdryer,Iron,Laptopfriendlyworkspace,
         Selfcheck_in,Smartlock,Privatelivingroom,Privateentrance,
         Hotwater,Bedlinens,Microwave,
         Refrigerator,Dishwasher,Dishesandsilverware,Cookingbasics,Oven,
         Stove,Gardenorbackyard,Privatelivingroom,Coffeemaker)
```


```{r }
#use mice to impute NA value of categorical variables
str(selection_scoringData)
View(colSums(is.na(selection_scoringData)))

selection_scoringData<-mice(selection_scoringData,m=1,method = "rf")
summary(data)
finished_selection_scoringData<-complete(selection_scoringData,1)
View(colSums(is.na(finished_selection_scoringData)))
```


```{r }
##split data
set.seed(1731)
split=sample(x=1:nrow(clean.data),size=0.75*nrow(clean.data))
split[1:10]
train=clean.data[split,]
test=clean.data[-split,]
```


```{r }
##vtreat
trt=designTreatmentsZ(dframe=train,
                      varlist=names(train[-1]))
newvars=trt$scoreFrame[trt$scoreFrame$code%in% c('clean','lev'),'varName']
train_input=prepare(treatmentplan=trt, 
                    dframe=train,
                    varRestriction = newvars)
test_input=prepare(treatmentplan=trt, 
                   dframe=test,
                   varRestriction = newvars)
str(train_input)
str(test_input)
```


```{r }
#tune
tune1=xgb.cv(data = as.matrix(train_input),
             label=train$price,
             nrounds = 100,
             nfold=5,
             verbose=0)
which.min(tune1$evaluation_log$test_rmse_mean) #find nrounds
set.seed(1031)
#xgboost
xgboost1=xgboost(data=as.matrix(train_input), 
                   label = train$price,
                   nrounds=93,
                   verbose = 0)
pred_train1= predict(xgboost1,newdata=as.matrix(train_input))
rmse_train_xgboost1 = sqrt(mean((pred_train1 - train$price)^2)); rmse_train_xgboost1
pred = predict(xgboost1, newdata=as.matrix(test_input))
rmse_xgboost1 = sqrt(mean((pred - test$price)^2));rmse_xgboost1
#scoring
str(finished_selection_scoringData)
trt_scoringdata = designTreatmentsZ(dframe=finished_selection_scoringData,
                                    varlist=names(finished_selection_scoringData))
newvars1 = trt_scoringdata$scoreFrame[trt_scoringdata$scoreFrame$code%in% c('clean','lev'),'varName']
scoringData_input = prepare(treatmentplan = trt_scoringdata, 
                            dframe = finished_selection_scoringData,
                            varRestriction = newvars1)
pred_scoring = predict(xgboost1,newdata=as.matrix(scoringData_input))
str(scoringData_input)
colnames(scoringData_input)
colnames(train_input)
levels(train_input$property_type)
levels(scoringData_input$property_type)
submissionFile = data.frame(id = scoringData$id, price = pred_scoring)
write.csv(submissionFile, '11.19sample_submission.csv',row.names = F)
```